

numpy.exceptions.AxisError
==========================

.. currentmodule:: numpy.exceptions



.. autoexception:: numpy::exceptions.AxisError

